### PR TITLE
meson: Basic meson support

### PR DESCRIPTION
**Pull request by mensinda**
With this patch, CLI11 can be used as a meson
subproject: http://mesonbuild.com/Subprojects.html

However, CMake is still required for testing and
installation. The current meson.build is not a
complete replacement.

### CODE REVIEW

**Comment by mensinda** [comment]
The Azure CI errors are unrelated.

**Comment by henryiii** [comment]
I plan to fix the CI then merge this, probably in the next few days...

**Comment by henryiii** [comment]
Could you rebase and force push (or just merge) with current master? Thanks!

**Comment by mensinda** [comment]
Done. Let's hope the CI gets green :)

**Comment by henryiii** [comment]
How hard would it be to add a new job to Azure to run meson with a little example project that uses this? (Not very familiar with Meson)

**Comment by mensinda** [comment]
Depends. That project would have to include the CLI11 repository in its's subproject directory. So, copying the CLI11 repo in the CI or a seperate repository would be required. Also python (>= 3.5), meson and ninja would be required on all images.

The actual project would be fairly simple and easy to provide, however, implementing this in the CI will probably the most difficult part.

**Comment by henryiii** [comment]
Could you provide the example project? I can probably set up the ci pretty easily. At the minimum, I could do a `brew install meson` on a mac image. We can symlink CLI11 into the directory as part of the test before running the meson build. I can merge this PR and we work in a new PR, or we can work in this PR, your call.

**Comment by mensinda** [comment]
Adding it to this PR should work. Do you have any preferences where to put the test?

**Comment by henryiii** [comment]
In a folder in the test folder. If it looks really useful as an example it might eventually be moved into the examples folder.

**Comment by mensinda** [comment]
Added the test project. Also a minimal README.md, in case this will be a meson example.

**Comment by henryiii** [comment]
This does not add the C++ standard setting, so it fails if you build on LLVM (or probably GCC < 6).

```
ccache c++ -Imain@exe -I. -I.. -I../subprojects/CLI11/include -Xclang -fcolor-diagnostics -pipe -Wall -Winvalid-pch -Wnon-virtual-dtor -g -MD -MQ 'main@exe/main.cpp.o' -MF 'main@exe/main.cpp.o.d' -o 'main@exe/main.cpp.o' -c ../main.cpp
```

(macOS)

**Comment by mensinda** [comment]
Should be fixed now (defaults to `c++11`)

**Comment by henryiii** [comment]
I believe it does not pick up the default (should be minimum...) C++ standard from a target. Not sure why this is supposed to be better than CMake... But, okay.

**Comment by henryiii** [comment]
It also does not regenerate correctly and has to have the build directory removed before it picks up the change...

**Comment by mensinda** [comment]
I mean, the C++ std is now `c++11` for the project by default with my changes. The default options are only applied when generating a new build directory. Changing options of an already existing directory has to be done with `meson configure`

**Comment by henryiii** [comment]
Yes, but I would have thought it would have made it C++11 because the sub-project was C++11, but that's not too bad. When I ran meson build again, it said that ninja would regenerate if necessary, but it did not because the build file changed. Just seems like usability issues.

**Comment by henryiii** [comment]
Should be ready to merge. Would you like it in examples instead of tests? I'd be okay with that.

**Comment by mensinda** [comment]
I would like to keep it in tests for now. It is a bit minimal for an example in the current state. Maybe I do a new PR in the future with a bit more content

**Comment by henryiii** [comment]
Okay. Thanks!

**Pull request merged**
