### PR TITLE
Add needs to subcommand

### PR DESCRIPTION
**Pull request by phlptp**
This PR will address #291 and #288 

it adds a needs function for subcommands and options to the app as well as a remove needs.  it also adds some alias operations to app so multiple subcommand names can represent a single subcommand.  

This will also work for nameless subcommands(option_groups) so the same group can be a subcommand or act just like regular options.

### CODE REVIEW

**Comment by phlptp** [comment]
- [x] write up readme documentation changes
- [x] a few tests of different callback ordering and the needs operation in context of argument ordering
- [x] a little more exploration of the implications of the aliases
- [x] get full code coverage

**Comment by phlptp** [comment]
I have run into a few issues with the interaction of needs and the callback operations and the fallthrough flag.  Still working on how to resolve these, but it will probably be a few days before things come together.

**Comment by phlptp** [comment]
This PR should also address #284 when finished

**Comment by phlptp** [comment]
#272 is also addressed, since the aliases needed to be checked as well

**Comment by phlptp** [comment]
In considering Aliases,  there is a possibility of conflict with existing subcommands and ignore_case, ignore underscore variants of such.   This required somewhat more complicated checking of the subcommand names.  But also in exploring it the ignore_case, ignore_underscore, name functions also did not currently check this, which means it was possible to generate conflicts.  So these checks were added and those functions were made exception safe.    more testing is required

**Comment by phlptp** [comment]
@henryiii I have been adding checks to make sure subcommands don't overlap in name or alias.  
Previously we were not checking overlap on the option_groups, so multiple option_groups could have the same subcommand name See [SameSubcommand](https://github.com/CLIUtils/CLI11/blob/b029b325b50389a2e11d6361c8b3112206bff56d/tests/OptionGroupTest.cpp#L523)  The question is do we want to allow this explicitly or not?  Basically should we allow the potential for using option_groups to have the same subcommand mean multiple different things if called multiple times.    

Options
1.  Disallow the same name to potentially reference multiple subcommands
2.  Allow the same name to reference multiple subcommands through option_groups(this is what is done currently)
3.  Add a flag that explicitly allows 2 if set to true.

**Comment by phlptp** [comment]
@henryiii   We would need a decision on 1,2 or 3 from the previous question to be able to move forward.  I don't really have a strong preference either way.   I was inclined towards option 1, but that would break an existing test case.

**Comment by phlptp** [comment]
So what I ended up doing with regard to subcommand names, is disable the check if the subcommand is disabled.  So if the existing behavior is needed there is a means of allowing it, but in general it would trigger an error.

**Comment by phlptp** [comment]
@henryiii I think something is wrong with the travis gcc 4.8 build and the azure clang 3.4 builds

**Comment by henryiii** [comment]
What's the current status? Do you think it's ready for a final review and merge?

**Comment by phlptp** [comment]
I think so, I haven't found anything I have wanted to change in a while.  I think there is a possibility of more work needed on the help output in relation to the changes from this PR, but I really don't know the best way to present that information yet and I think it will take some experience using it to know for sure.

**Review by henryiii — APPROVED** [review]

**Comment by henryiii** [comment]
I think it looks good enough to merge. We can adjust things like help output in the future.

**Pull request merged**
