### PR TITLE
missing function definition

### PR DESCRIPTION
**Pull request by phlptp**
the get_option_group definition was missing from the splitting of the definitions. 

I tried to compile the single header into our code and discovered a missing function call.

### CODE REVIEW

**Comment by phlptp** [comment]
Need to merge #794 first, that should fix the tests

**Comment by henryiii** [comment]
Ouch, is this a regression? Do we know why it was passing tests?

**Comment by phlptp** [comment]
I think the recent pre-commit update changed something and introduced a cyclic change in some files that pre-commit couldn't resolve on its own.  And I didn't want to make a bunch of unrelated doc changes in this PR.  As to the original problem yes I think it was a regression but I am still trying to figure out why this wasn't triggering some issues with the single header tests or the other tests for that matter.   What I know is tried updating the single header CLI11 used in other applications and it generated a linking error which led to a missing definition.

**Comment by henryiii** [comment]
It does complain that it's completely untested.

**Comment by henryiii** [comment]
And I'm not seeing a test for it.

**Comment by phlptp** [comment]
I will add some tests

**Comment by henryiii** [comment]
Looks like we can do a .1 release after this, no new features have gone in yet AFAICT.

**Comment by phlptp** [comment]
as long as we do it before merging #789 and #786, that should be fine.

**Pull request merged**
