### PR TITLE
Issue 70

### PR DESCRIPTION
**Pull request by SkyToGround**
Implements the feature suggested in issue #70. I will be happy to make changes to the feature if you feel any are required in order to merge the code with master.

### CODE REVIEW

**Comment by henryiii** [comment]
PS: It's okay if formatting doesn't pass, I can auto-fix formatting trivially.

**Comment by henryiii** [comment]
Is this inheritable? It is labeled as such, but didn't see it the inheriting part of the code in the diff. I might have missed it, though. I can add it if you need me too.

**Comment by SkyToGround** [comment]
Sorry, that was my mistake. Please tell me (or fix) if I have made other mistakes.

**Comment by henryiii** [comment]
LGTM, thanks!

**Pull request merged**
