### PR TITLE
Added missing virtual App::~App()

### PR DESCRIPTION
**Pull request by delpinux**
It was detected by clang++7

### CODE REVIEW

**Comment by henryiii** [comment]
Great, thanks! Will merge as soon as tests pass. 👍

**Comment by delpinux** [comment]
Hmm... looks like I failed with the style pass :)
Should I fixe it?

**Comment by henryiii** [comment]
Normally, I'd recommend using `git commit --amend` and `git push -f` if you are in a PR or branch (never master) to keep history clean for a small style-related change. But this is just fine for this PR, I'll use squash and merge. :)

**Comment by delpinux** [comment]
Ok.
Thanks for this nice library, keep up the good work :+1:

**Pull request merged**
