### PR TITLE
format the CLI11_PARSE formart

### PR DESCRIPTION
**Pull request by aengusjiang**
clean the code

### CODE REVIEW

**Comment by phlptp** [comment]
This would be a pretty big breaking change.   
Going from a `;` optional to now required.  
and only accepting the 2 argument form of parse for the macro.  

Arguably it should have been wrapped in a do/while loop from the beginning and all the examples use a `;` but I don't know that all user code is currently, and I have used the single argument parse with the macro in the past.

**Comment by aengusjiang** [comment]
This pr main consider that when we write a code such such as function call it will be like fun();
Bug the in macro CLI11_PARSE define with a ';',  it is strange the write a code like:CLI11_PARSE() without ';', 
it is pretty that CLI11_PARSE(); but it has double ';'. 

so this pr can make the code more standard. the change consider the compatiable it good. but I think remote the ';' in  the macro is more more better.

**Comment by phlptp** [comment]
While I agree with you, I don't think we can make this change until we would move to a 3.0 release as it would be a breaking change.

**Comment by henryiii** [comment]
The two argument change was due to the recent merge, I think. This didn't start by forcing the semicolon, so we shouldn't force it now, it would break a lot of existing code. I've also always thought that form was weird - and IIRC, it tripped up a compiler (nvcc, perhaps?) when I was developing it, so I left it off.

**Pull request closed without merging**
