### PR TITLE
Add non-const version of App::get_options

### PR DESCRIPTION
**Pull request by jbriales**
Addressing missing function as discussed in #326

### CODE REVIEW

**Comment by jbriales** [comment]
Any ideas/hints about the failures above?

**Comment by phlptp** [comment]
The CI failures look like the same thing that is happening to the other PR's so I am assuming once those get fixed this can be rerun as well.

**Comment by henryiii** [comment]
Please rebase and force-with-lease, please. CI should be fixed. You might need to run pre-commit, but unlikely.

I'll do it if you need me to.

**Comment by jbriales** [comment]
Seems it's all good now? :)

**Comment by henryiii** [comment]
I'm surprised this still reports 100% coverage. Has a test started using this version, but not all of them? Odd. Regardless, I think it's fine.

**Comment by henryiii** [comment]
Thanks!

**Comment by phlptp** [comment]
Pretty sure a number of the tests that use that function would be based on non-const, but the actual formatters and several other functions use a const pointer , so they would still use the const version.    At some point a test probably should be added specifically to test the differences between the two versions.

**Comment by jbriales** [comment]
I was also expecting test coverage would fail but I guess as you say the const vs non-const difference is subtle.
I created a new pull request to add the corresponding unit test in https://github.com/CLIUtils/CLI11/pull/337.

**Pull request merged**
