### PR TITLE
fix: only use CPack if this is the main project

### PR DESCRIPTION
**Pull request by henryiii**
Alternative fix to, and closes #900.

### CODE REVIEW

**Comment by Jo5ta** [comment]
it would also be nice to have also a option to enable this.

**Comment by henryiii** [comment]
Why? If you want to pack CLI11 into a parent project, I don't think this works, does it? I don't think CPack is aware of subprojects. Though I'm not sure about that.

**Comment by henryiii** [comment]
Most of the variables don't seem to be useful in the context of a superproject, IMO. The parent project would want to set its own name - CPACK_DEBIAN_PACKAGE_NAME isn't correct if you aren't CLI11! Etc. I don't think anything would be reusable if you aren't running CLI11 directly.

**Comment by phlptp** [comment]
I was thinking I might want a variable to disable this normally.  Since most of the time I don't want any packaging regardless if it was  the main project or not.    Then if it was enabled by default if it is the main project, disabled by default if it was not, either way in the unusual use cases where you want something different, there is a variable setting that can change it.

**Comment by henryiii** [comment]
It doesn't package by default - you have to run CPack. The only thing this does is set some variables and add two targets (that you don't have to build - they are not in ALL).

**Pull request merged**
