### PR TITLE
Fix C++ standard, should be 2017

### PR DESCRIPTION
**Pull request by barracuda156**
It does not build with C++11, and compiler explicitly asks for C++17.

### CODE REVIEW

**Comment by barracuda156** [comment]
Here is what happens with C++11 being required (gcc still chooses C++14, and that still fails):
```
In file included from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_CLI11/CLI11/work/CLI11-2.4.0/include/CLI/StringTools.hpp:266,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_CLI11/CLI11/work/CLI11-2.4.0/include/CLI/CLI.hpp:20,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_CLI11/CLI11/work/CLI11-2.4.0/tests/applications/ensure_utf8_twice.cpp:7:
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_CLI11/CLI11/work/CLI11-2.4.0/include/CLI/impl/StringTools_inl.hpp:218:19: error: 'uint32_t' in namespace 'std' does not name a type; did you mean 'wint_t'?
  218 | CLI11_INLINE std::uint32_t hexConvert(char hc) {
      |                   ^~~~~~~~
      |                   wint_t
In file included from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_CLI11/CLI11/work/CLI11-2.4.0/include/CLI/CLI.hpp:14:
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_CLI11/CLI11/work/CLI11-2.4.0/include/CLI/Macros.hpp:129:22: warning: inline variables are only available with '-std=c++17' or '-std=gnu++17' [-Wc++17-extensions]
  129 | #define CLI11_INLINE inline
      |                      ^~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_CLI11/CLI11/work/CLI11-2.4.0/include/CLI/impl/StringTools_inl.hpp:232:1: note: in expansion of macro 'CLI11_INLINE'
  232 | CLI11_INLINE char make_char(std::uint32_t code) { return static_cast<char>(static_cast<unsigned char>(code)); }
      | ^~~~~~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_CLI11/CLI11/work/CLI11-2.4.0/include/CLI/impl/StringTools_inl.hpp:232:34: error: 'uint32_t' is not a member of 'std'; did you mean 'wint_t'?
  232 | CLI11_INLINE char make_char(std::uint32_t code) { return static_cast<char>(static_cast<unsigned char>(code)); }
      |                                  ^~~~~~~~
      |                                  wint_t
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_CLI11/CLI11/work/CLI11-2.4.0/include/CLI/impl/StringTools_inl.hpp:234:59: error: 'std::uint32_t' has not been declared
  234 | CLI11_INLINE void append_codepoint(std::string &str, std::uint32_t code) {
      |                                                           ^~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_CLI11/CLI11/work/CLI11-2.4.0/include/CLI/impl/StringTools_inl.hpp: In function 'void CLI::detail::append_codepoint(std::string&, int)':
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_CLI11/CLI11/work/CLI11-2.4.0/include/CLI/impl/StringTools_inl.hpp:239:32: error: 'CLI::detail::make_char' cannot be used as a function
  239 |         str.push_back(make_char(0xC0 | code >> 6));
      |                       ~~~~~~~~~^~~~~~~~~~~~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_CLI11/CLI11/work/CLI11-2.4.0/include/CLI/impl/StringTools_inl.hpp:240:32: error: 'CLI::detail::make_char' cannot be used as a function
  240 |         str.push_back(make_char(0x80 | (code & 0x3F)));
      |                       ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_CLI11/CLI11/work/CLI11-2.4.0/include/CLI/impl/StringTools_inl.hpp:246:32: error: 'CLI::detail::make_char' cannot be used as a function
  246 |         str.push_back(make_char(0xE0 | code >> 12));
      |                       ~~~~~~~~~^~~~~~~~~~~~~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_CLI11/CLI11/work/CLI11-2.4.0/include/CLI/impl/StringTools_inl.hpp:247:32: error: 'CLI::detail::make_char' cannot be used as a function
  247 |         str.push_back(make_char(0x80 | (code >> 6 & 0x3F)));
      |                       ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_CLI11/CLI11/work/CLI11-2.4.0/include/CLI/impl/StringTools_inl.hpp:248:32: error: 'CLI::detail::make_char' cannot be used as a function
  248 |         str.push_back(make_char(0x80 | (code & 0x3F)));
      |                       ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_CLI11/CLI11/work/CLI11-2.4.0/include/CLI/impl/StringTools_inl.hpp:251:32: error: 'CLI::detail::make_char' cannot be used as a function
  251 |         str.push_back(make_char(0xF0 | code >> 18));
      |                       ~~~~~~~~~^~~~~~~~~~~~~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_CLI11/CLI11/work/CLI11-2.4.0/include/CLI/impl/StringTools_inl.hpp:252:32: error: 'CLI::detail::make_char' cannot be used as a function
  252 |         str.push_back(make_char(0x80 | (code >> 12 & 0x3F)));
      |                       ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_CLI11/CLI11/work/CLI11-2.4.0/include/CLI/impl/StringTools_inl.hpp:253:32: error: 'CLI::detail::make_char' cannot be used as a function
  253 |         str.push_back(make_char(0x80 | (code >> 6 & 0x3F)));
      |                       ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
. . .
```

**Comment by barracuda156** [comment]
See also, as an example of a similar issue: https://github.com/pytorch/FBGEMM/issues/1470#issuecomment-1516661793

**Comment by henryiii** [comment]
Does https://github.com/CLIUtils/CLI11/pull/996 fix this?

**Comment by barracuda156** [comment]
> Does #996 fix this?

@henryiii Let me try.

UPD. Yes, that works too, closing this one.

**Pull request closed without merging**
